### ISSUE TITLE
Doubts to implement

### ISSUE THREAD

**Issue by likith1908** [npurson/fid-metrics#1]
1. I am using a MacBook Air M1, will that be any problem with implementing this?

2. What are path1 and path2? in the following line
 ```
 python fid_metrics/main.py paths=[path1,path2] 
 ```
3. Should i provide file paths or folder paths?

Thanks

**Comment by npurson** [comment]
path1 and path2 should be folder paths (or glob patterns that match a series of images) used to calculate the FID distance.

I'm not familiar with torch on M1 chips, as long as torch can use CUDA or CPU with M1 chips, I think it would be fine.

I’m not familiar with PyTorch’s performance on the M1 chip. As long as PyTorch supports running on CUDA or the CPU with M1 chips, I suppose it should work fine.

**Comment by likith1908** [comment]
Can we give videos as inputs or we should convert videos to series of images?

**Comment by npurson** [comment]
It supports video inputs as well. You can refer to [here](https://github.com/npurson/fid-metrics/blob/91746270b16d3503c3e8961a15a20461e414142a/fid_metrics/main.py#L26) for more details.

**Comment by pranav190232** [comment]
i am running this repo on windows can u guide me on how to run code like what should i put in path1 and 2

**Comment by likith1908** [comment]
> It supports video inputs as well. You can refer to [here](https://github.com/npurson/fid-metrics/blob/91746270b16d3503c3e8961a15a20461e414142a/fid_metrics/main.py#L26) for more details.

Path1 is for real videos which we consider as ground truth and path2 is for synthetic videos right?

**Comment by npurson** [comment]
> > It supports video inputs as well. You can refer to [here](https://github.com/npurson/fid-metrics/blob/91746270b16d3503c3e8961a15a20461e414142a/fid_metrics/main.py#L26) for more details.
> 
> Path1 is for real videos which we consider as ground truth and path2 is for synthetic videos right?

There is no issue here, but to clarify, the FID distance measures the difference between two videos without distinguishing which one is the ground truth.

**Comment by likith1908** [comment]
Okay, thanks

Regards
Likith Gannarapu
Student
Mahindra University
