### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by pranav190232** [npurson/fid-metrics#2]
python fid_metrics/main.py paths=[C:\Users\prana\OneDrive\Desktop\Synthetic evaluation\videos,C:\Users\prana\OneDrive\Desktop\Synthetic evaluation\synthetic videos]
no viable alternative at input '[C:\Users\prana\OneDrive\Desktop\Synthetic'
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
(synt) PS C:\Users\prana\OneDrive\Desktop\Synthetic evaluation> 

i ran the code its not working

**Comment by npurson** [comment]
There is a space in your path. You should wrap it in quotes, e.g., `python main.py paths=['xxx xxx',xxx]`.
