### ISSUE TITLE
为什么frame_idx是负数

### ISSUE THREAD

**Issue by mate-huaboy** [npurson/fid-metrics#4]
https://github.com/npurson/fid-metrics/blob/91746270b16d3503c3e8961a15a20461e414142a/fid_metrics/dataset.py#L123
这里的计算frame_idx 为负，cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)应该会失效吧，期望得到您的解答

**Comment by npurson** [comment]
frame_idx 不应该是负的呀，这里的意思是因为 idx 其实是多个视频中的索引，要找到其在单个视频中的索引，需要减去这个视频之前所有帧的数量。我之前这般代码应该运行没有问题，您那边报错了吗？

**Comment by mate-huaboy** [comment]
您好，我这边没有报错，但是调试的时候发现这个frame_idx是个负数，似乎这里是一个bug,可以帮忙一块看看吗，万分感谢

**Comment by mate-huaboy** [comment]
1. 代码中这个idx是从0开始的，bisect.bisect_left(self.num_accum_sequences, idx) 获取的video_idx有误2.求frame_idx时，似乎需要减去前一个视频的num_accum_sequences，而不是当前的。我这边试着粗糙的修复了一下，感谢您开源的作品。

![20241224-130015](https://github.com/user-attachments/assets/cc9d4847-9b64-4f79-9d95-1354cda4444c)

**Comment by npurson** [comment]
感谢反馈，您改的应该是对的，我稍后修复一下
